### ISSUE TITLE
Is there a Raspbian driver available?

### ISSUE THREAD

**Issue by Olifiers** [pimoroni/trackball-python#3]
This is more of a request for clarification than an issue. It's suggested that there's a Raspbian mouse driver for the trackball, but I'm unsure if that's really the case and, if that's so, how to install it.

**Comment by Gadgetoid** [comment]
The best approach for a driver is to use `evdev-mouse.py` since it's more stable and less resource intensive than the basic `mouse.py` which calls out to an external binary.

The setup instructions for it are now in the new README.md here - https://github.com/pimoroni/trackball-python/tree/master/examples

To use it as a mouse driver it should probably be installed as a systemd service- I could probably whip up a quick script to make that easier.

**Comment by Gadgetoid** [comment]
Done! See updated instructions here: https://github.com/pimoroni/trackball-python/tree/master/examples

**Comment by Olifiers** [comment]
This is perfect, thanks!!!
