### ISSUE TITLE
INT Signal polled?

### ISSUE THREAD

**Issue by rmwphd** [pimoroni/trackball-python#9]
https://forums.pimoroni.com/t/pim447-trackball-how-to-get-a-clean-int-signal/17968

See above thread on the pimoroni forums. It seems the INT signal is polled? This means this trackball is not suitable for wireless use. Can this be fixed, or is it hardware related?

**Comment by smeikx** [comment]
This issue has been stale for too long … really disappointing.

**Comment by Gadgetoid** [comment]
It's a work in progress - https://github.com/pimoroni/pimoroni-pico/issues/357

**Comment by rmwphd** [comment]
Anything I could do to help? I have some of these trackballs handy if you need someone to test. One is installed on a keyboard with microcontroller sockets and I have both nice!nano and Elite-C controllers I can use with it

**Comment by Gadgetoid** [comment]
They use a Nuvoton MS51 (MS51XB9AE) and are a little bit of a pig to program. Needs a Nu-Link-Me v3.0 or similar and the programming tools only seem to be available for windows (and I've migrated fully to Linux *sigh*)

If you fancy a challenge and can find a Nu Link programmer, the square test pad on the back is the "/reset" line, VCC/GND as as you would expect, SDA/SCL map to NU Link's ICE_DAT/ICE_CLK and "INT" is N/C.

My attempts to find some Linux-compatible or more accessible way to flash these have failed so - once the fix is tested and confirmed working - we will probably send out replacements for those who really need the interrupt functionality.

**Comment by DelusionalLogic** [comment]
Is there a possibility of open sourcing, or at least sharing the source firmware? From my testing it seems like the interrupt functionality works (with a little bit of a software workaround for the errata), but I'm seeing pretty bad tracking that seems to somehow be tied to the speed I can service interrupts. I'm down to <400 micros, but the tracking is still pretty bad.

I'm worried it's tied to this issue.

**Comment by alexmaloteaux** [comment]
the interrupt pin is fixed on latest firmware : https://github.com/pimoroni/pimoroni-pico/issues/357#issuecomment-1304868559

**Comment by ageeandakeyboard** [comment]
Thanks @alexmaloteaux for chiming in on this issue.
I'll close it now
